name: build
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: pnpm/action-setup@v4
              with:
                  version: 10.18.3
                  run_install: false
            - uses: actions/setup-node@v5
              with:
                  node-version: "24"
                  check-latest: true
            - run: pnpm install
            - run: pnpm build
